### ISSUE TITLE
panic when identical patterns are registered

### ISSUE THREAD

**Issue by rogpeppe** [go-chi/chi#313]
Multiple versions of the same pattern can be registered without complaint, which hides something that's almost certainly a mistake. This also removes the useful property that registration order is unimportant - because a different handler will be used if they're registered in a different order.

Perhaps consider panicking in this case.

	package main
	
	import (
		"fmt"
		"net/http"
		"net/http/httptest"
	
		"github.com/go-chi/chi"
	)
	
	func main() {
		mux := chi.NewMux()
		mux.Method("GET", "/foo", handler{1})
		mux.Method("GET", "/foo", handler{2})
		srv := httptest.NewServer(mux)
		http.Get(srv.URL + "/foo")
	}
	
	type handler struct {
		id int
	}
	
	func (h handler) ServeHTTP(w http.ResponseWriter, req *http.Request) {
		fmt.Printf("called %v\n", h.id)
	}

**Comment by pkieltyka** [comment]
presently, the last route definition for a pattern is what registered... previous routes will be overridden. This is made somewhat by design for scenarios to override the route for a mounted subrouter. I'd like to maintain that, but, an option is to wrap the chi.Router interface with your own Router that makes this check.
