### ISSUE TITLE
regex router doesn't match static file

### ISSUE THREAD

**Issue by todylu** [go-chi/chi#360]
Because of server side render of angular/react, expressjs can be used like below:
```
// match all of  js and css file
app.get('*.*', express.static(DIST_FOLDER, {
  maxAge: '1y'
}));
// All regular routes use the Universal engine
app.get('*', (req, res) => {
  res.render('index', { req });
});
```
So, when I migrate to golang/chi, I try to use the route like below:
```
// match all of  js and css file
r.Get("/{file:.*\\.(js|css|jpg)}", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	http.FileServer(http.Dir(*dir)).ServeHTTP(w, r)
}))
// All regular routes use the Universal engine via RPC
r.Get("/*", render(... ...)))
```
But, js and css files would match `/*`

**Comment by pkieltyka** [comment]
the issue might be the way http.FileServer builds path's internally with chi's router. Perhaps I should make a separate middleware that better works with chi for file serving, but unfortunately I don't have the time. I did however check the routing path on a local example and it worked just fine. I suspect the issue is `r.Get("/*", render(...))`` and the paths not being joined correctly
