### ISSUE TITLE
Remove/replace routes

### ISSUE THREAD

**Issue by innovate-invent** [go-chi/chi#480]
Is it possible to remove or replace routes?

**Comment by mfridman** [comment]
With this pkg you define the named routes and associated handlers. With middleware you'd control flow.

You may want to elaborate on the question.. what are you trying to do?

**Comment by innovate-invent** [comment]
All of the examples show building the router up and then passing it to http.ListenAndServe.
Ideally I want to be able to keep a handle to the base router and modify it after Serve().
Digging through the tree code it appears there is no way to remove routes or middleware.

**Comment by vtolstov** [comment]
Yes, this can be useful

**Comment by pkieltyka** [comment]
whats the use case / scenario for removing routes? if you require that, you should probably think to break apart your router into parts and join it together as you need depending on flow

**Comment by vtolstov** [comment]
I'm plan to use it on api gateway.
So when some service started new routes must be added, when service stopped, routes must be removed

**Comment by mfridman** [comment]
Interesting. What's the benefit of building an api gateway using a generic router such as this one, where you mount/unmount routes dynamically at runtime?

Say a request comes in, the route was previously **unmounted**, what happens?

Why not encapsulate the logic of that routed unit into a single microservice with own router and when the microservice "dies" so do the routes?

I'd imagine if you want dynamic un/mounting of routes it should be a concern of the api gateway service _itself_, i.e., something would need to maintain state of routes that are "on/off".

Sorry @pkieltyka, I know this isn't really an _issue_ but I'm genuinely curious.

**Comment by mfridman** [comment]
fwiw, you may want to take a look at the `routerSwap` approach. I've seen this come up a few times over the years, but could never understand why you'd want this as part of the router pkg.

https://github.com/gorilla/mux/issues/82#issuecomment-121411186

**Comment by innovate-invent** [comment]
the routerswap approach would work for replacing, but what about removing routes?

**Comment by vtolstov** [comment]
@mfridman when the route is removed , you must returns 404 not found. As no service can process request and path not handled. Encapsulation to additional service means that you need to transfer all data to it and it must works as proxy. This is additional spof, or it must be distributed..

**Comment by pkieltyka** [comment]
this isn't something I'm planning to add to the core, it belongs outside of the router, for example, create a new one and mount/swap outside above the individual router

**Comment by masseelch** [comment]
I have another use case: I am code generating simple crud handlers for all my entities. Sometimes i want to be able to swap some of the generated methods out for another one (so i do not need the removing part). 

Currently i have a huge amount of configuration, so some of the routes for some entities are not getting generated so i can pass in some custom logic.

**Comment by awagner-mainz** [comment]
I am sorry if this is not an appropriate place to ask this: I have a setup where I generate lots of new routes regularly (kind of DOI redirections from a ID'ed URI to an actual html file that has another name, so no simple pattern replacement). I was thinking there should be a router somewhere that has its routing table in a key-value store or another database-like structure where you can add (and remove) routes in runtime. However, Chi and this issue is the closest I could find.

Do I have a wrong idea of what I need? Otherwise, would that make a use case for Chi - or, if this will not be integrated in the Chi core, do you think it can be added on top of it more or less easily?

**Comment by innovate-invent** [comment]
@awagner-mainz you would just create a handler that does the kv lookup and responds accordingly. You can use the router path variables provided by chi to build the key for the kv

**Comment by mfridman** [comment]
@awagner-mainz Could you accomplish the redirections using dynamic URL parameters? Instead of telling the chi router your k/v mapping .. instead push that down to your application code?

e.g., say you're sending a request to http://dx.doi.org/10.1109/MIC.2009.93 in chi you could model it like so:

```
.Get("/{doi_id}/{ident_id}", DOIRedirect)
```

and then your `DOIRedirect` handler (which itself can have access to some k/v or DB store) will grab those dynamic elements `doi_id` + `ident_id` and handle dynamically looking up the html and/or handling the redirects.

**Comment by awagner-mainz** [comment]
D'uh! You're right of course! I guess I needed that push in the right direction. Thank you both, @mfridman and @innovate-invent .
