### ISSUE TITLE
Is this code the same in terms of performances? .Get(), .Post() or .Handle()

### ISSUE THREAD

**Issue by frederikhors** [go-chi/chi#520]
I'm trying to understand if there is a performance decrease using [`go-chi`](https://github.com/go-chi/chi)'s `Handle()` method.

I need to use both `GET` and `POST` endpoints with the same handler.

**Is it better to use this code**:
```go
func main() {
	handler := NewAPIHandler(myOptions)

	r := chi.NewRouter()

	r.Group(func(r chi.Router) {
		r.Use(middlewares)
		r.Get("myEndpoint", handler)
		r.Post("myEndpoint", handler)
	})
}
```

**Or this code?**

```go
func main() {
	handler := NewAPIHandler(myOptions)

	r := chi.NewRouter()

	r.Group(func(r chi.Router) {
		r.Use(middlewares)
		r.Handle("myEndpoint", handler)
	})
}
```

**Or is the same?**

**Comment by pkieltyka** [comment]
@frederikhors the performance will be identical, both methods are added to the tree as identical structures. The performance the router of considered when searching the tree for the route which is when a request is passed from the server to the chi.Mux ServeHTTP method, which will then call the find method of the tree. The tree is built and inserted at time of instantiation of the router and then that structure is cached. 

the only difference is that .Handle() will register on all request methods for "myEndpoint", where as the specific .Get() and .Post() calls will register only on those specific methods. Handle is like a wildcard for http methods, which is useful when you want to stack routers or defer handling to an another handler from that point forward, ie. r.Handle("/admin/*", adminRouter).  In general, always try to specify the http method of the endpoint if you can so its designed with intentional use -- but performance will be the same.
