### ISSUE TITLE
If no any handler defined, then all middlewares will be ignored but it should not.

### ISSUE THREAD

**Issue by lunny** [go-chi/chi#557]
Ref: https://github.com/go-gitea/gitea/issues/13725

When building a router, static files are handled in a middleware and there is no any handler. Then all middlewares are ignored. But I think that should NOT be expected. Middlewares should be always executed because it may send response but not continue the chain.

https://github.com/go-chi/chi/blob/master/mux.go#L60-L65

**Comment by pkieltyka** [comment]
How are static file routes handled without a route? Can you post example

**Comment by lunny** [comment]
One example from Gitea is here https://github.com/go-gitea/gitea/blob/master/routers/routes/chi.go#L118 . The middleware will check the METHOD and request path prefix to decide if `next` will be invoked or just write to response.

**Comment by pkieltyka** [comment]
After further investigation, the chi implementation and design is correct. You'll need to define a handler/route in order to use the Mux. Alternatively you can use chi.Chain(middlewares), however, this as well requires a http.Handler or http.HandlerFunc.

I understand the point you bring up and from outside seems reasonable at first glance, but for the purposes of "correctness" and efficiency, there is no viable solution to allow what you're requesting. The solution is to specify a handler.

**Comment by lunny** [comment]
I don't think so. I think maybe it's better to panic if there is no any handler rather than ignoring all the middlewares and always handle NotFound handler.

**Comment by pkieltyka** [comment]
Or perhaps return a 5xx error instead of a panic
