### ISSUE TITLE
Static extension pattern in url param is not working as expected

### ISSUE THREAD

**Issue by arch-mage** [go-chi/chi#619]
Router pattern does not work as expected when it statically ended with specific extension. For example, this one (the `Match` call) evaluate to `false`:

```go
package main

import (
    "github.com/go-chi/chi/v5"
)

func main() {
    app := chi.NewMux()
    app.Get("/{name}-{version}.tgz", nil)
    app.Match(chi.NewRouteContext(), "GET", "/name-1.0.0.tgz") // this should be true
}
```

But, this one evaluate to `true`:
```go
func main() {
    app := chi.NewMux()
    app.Get("/{name}-{version}-tgz", nil)
    app.Match(chi.NewRouteContext(), "GET", "/name-1.0.0-tgz")
}
```

If this is not by design, I think this is a bug.

**Comment by pkieltyka** [comment]
Yes I recall something like this -- it's a tricky one as parsing occurs on the ".". This will be a tough one to solve, but feel free to submit a PR if you can pull it off :D

The other approach which will get you by.. is route on.. `/{filename}` and then parse the filename yourself instead of depending on the routing pattern to split the version out
