### ISSUE TITLE
Possible bug can lead to security issue

### ISSUE THREAD

**Issue by lfama** [go-chi/chi#886]
Hi there,

I believe I found a bug that can lead to a security issue in some scenarios. I've noticed that the repository doesn't have a Security policy, so I'm not sure how to report it. Could you please let me know which is the right channel to report the issue?

Thanks!

**Comment by pkieltyka** [comment]
hi there, feel free to send me DM on twitter @peterk

**Comment by peterk** [comment]
@peterk is me so better to send it to @pkieltyka :-)

**Comment by lfama** [comment]
Hi @pkieltyka, it looks like I can't DM you on X/Twitter

**Comment by pkieltyka** [comment]
I opened my DMs, can you try again?On Dec 18, 2023, at 1:56 PM, lfama ***@***.***> wrote:﻿
Hi @pkieltyka, it looks like I can't DM you on X/Twitter

**Comment by pkieltyka** [comment]
@lfama I opened my DMs, can you try again?

**Comment by peterk** [comment]
Please untag me @pkieltyka :-)

**Comment by pkieltyka** [comment]
peterk -- github may have auto-tagged you, can you click the "unsubscribe" button? I'm not aware of any other way to untag you

**Comment by pkieltyka** [comment]
thank you @lfama for the report. Feel free to add any additional details to this ticket if you'd like too :)

@lfama had found an issue which was introduced from the community PR https://github.com/go-chi/chi/pull/776. The faulty behaviour was that the "Allow" header on 405 responses and was not properly reset in the request context between requests, which are reused via a sync.Pool -- as a result, the "Allow" header was returned and repeated multiple times to clients. 

The fix is: https://github.com/go-chi/chi/commit/9dd8b4a7b5930c86ac2ecfdb55467112cc223518 to reset the buffer before using the context.

I've published a new release v5.0.11, https://github.com/go-chi/chi/releases/tag/v5.0.11

Thanks again @lfama 🥇
